#!/usr/bin/env python3
"""Bootstrap clustered by customer for the comparison system vs. logistic regression.

Produces: the logistic row of data/ranking-comparison-by-customer-2026-09-05.csv
(the interval [−0.0846; +0.0381] and the 21.1% of non-negative replicates).
Supports: Table 2, the verdict of the eighth comparison under the declared
estimator; the seventh row of Table 6.

Why it exists. Table 2 reports the bootstrap clustered by customer — the estimator
the pre-registration declares — for the seven rankings by attribute; for the
eighth, the logistic regression, it had not been computed, so the verdict of the
decisive comparison came from the undeclared estimator. This script closes that
gap without re-estimating the logistic regression: it takes the SQL GENERATED by
`logistic_baseline.py` (`sql/logistic-evaluation.sql`, with the coefficients of
the 23 August fit injected), cuts the query at the point where the `ndcg` CTE is
complete, and appends the same bootstrap block as
`sql/ranking-comparison-by-customer.sql` — same seed, same one thousand
replicates, same rule that a drawn customer enters with all of its requests.

It does not edit the generated file: it writes
`sql/logistic-bootstrap-by-customer.sql`, which is derived and kept so that the
execution is reproducible, and runs it through `scripts/run-sql.sh`.

Usage:
    python3 scripts/bootstrap_logistic.py --dry-run
    python3 scripts/bootstrap_logistic.py
"""
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / "sql/logistic-evaluation.sql"
TARGET = ROOT / "sql/logistic-bootstrap-by-customer.sql"
# The marker is the comment line that opens the by-request estimation block in
# the generated SQL, immediately after the `ndcg` CTE closes.
CUT = "-- THE RESAMPLING UNIT IS THE CUSTOMER"

TAIL = """
-- ============================================================================
-- Derived by `bootstrap_logistic.py` from the generated logistic evaluation:
-- bootstrap clustered by CUSTOMER of the NDCG@5 difference system − logistic,
-- with the seed and the one thousand replicates of
-- `ranking-comparison-by-customer.sql`.
-- ============================================================================
, customer_indexed AS (
  SELECT tenant_id,
         ROW_NUMBER() OVER (ORDER BY FARM_FINGERPRINT(CAST(tenant_id AS STRING))) - 1 AS idx
  FROM (SELECT DISTINCT tenant_id FROM ndcg WHERE n_system IS NOT NULL AND n_logistic IS NOT NULL)
),
size AS (SELECT COUNT(*) AS n FROM customer_indexed),
draw AS (
  SELECT r AS replicate,
         MOD(ABS(FARM_FINGERPRINT(CAST(r * 1000003 + i AS STRING))), (SELECT n FROM size)) AS idx
  FROM UNNEST(GENERATE_ARRAY(1, 1000)) AS r,
       UNNEST(GENERATE_ARRAY(0, (SELECT n FROM size) - 1)) AS i
),
replicate_diff AS (
  SELECT s.replicate, AVG(x.n_system - x.n_logistic) AS d
  FROM draw s
  JOIN customer_indexed e USING (idx)
  JOIN ndcg x USING (tenant_id)
  WHERE x.n_system IS NOT NULL AND x.n_logistic IS NOT NULL
  GROUP BY s.replicate
)
SELECT
  'system - logistic_5var'                                     AS comparison,
  (SELECT n FROM size)                                         AS customers,
  COUNT(*)                                                     AS replicates,
  ROUND(AVG(d), 4)                                             AS mean_difference_bootstrap_customer,
  ROUND(APPROX_QUANTILES(d, 1000)[OFFSET(25)],  4)             AS ci95_low_bootstrap_customer,
  ROUND(APPROX_QUANTILES(d, 1000)[OFFSET(975)], 4)             AS ci95_high_bootstrap_customer,
  ROUND(COUNTIF(d >= 0) / COUNT(*), 4)                         AS fraction_replicates_non_negative
FROM replicate_diff;
"""


def main() -> int:
    text = GENERATED.read_text(encoding="utf-8")
    if CUT not in text:
        sys.exit(f"cut marker not found in {GENERATED.name}")
    head = text.split(CUT)[0].rstrip()
    assert head.rstrip().endswith(")"), "the cut did not end at the close of the ndcg CTE"
    sql = head + "\n" + TAIL
    tmp = TARGET.with_suffix(".tmp")
    tmp.write_text(sql, encoding="utf-8")
    tmp.replace(TARGET)
    print(f">> written {TARGET.relative_to(ROOT)} ({len(sql.splitlines())} lines)")
    args = ["./scripts/run-sql.sh", str(TARGET.relative_to(ROOT))]
    if "--dry-run" in sys.argv:
        args.append("--dry-run")
    return subprocess.call(args, cwd=ROOT)


if __name__ == "__main__":
    sys.exit(main())
